apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: ai-soc
  labels:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/part-of: ai-soc-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: opensearch
  ports:
    - name: http
      port: 9200
      targetPort: http
      protocol: TCP
    - name: transport
      port: 9300
      targetPort: transport
      protocol: TCP
