import time
import uuid

from fastapi import APIRouter, Depends
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.models.ai_analysis import AIAnalysis
from app.models.incident import Incident
from app.schemas.ai import (
    AIAnalyzeRequest,
    AIAnalyzeResponse,
    AIIncidentAnalysis,
    AISummarizeRequest,
    AISummarizeResponse,
)

router = APIRouter()


@router.post("/analyze", response_model=AIAnalyzeResponse)
async def analyze_security_query(
    request: AIAnalyzeRequest,
    db: AsyncSession = Depends(get_db),
):
    start_time = time.time()

    context_parts = []
    if request.incident_id:
        result = await db.execute(select(Incident).where(Incident.incident_id == request.incident_id))
        incident = result.scalar_one_or_none()
        if incident:
            context_parts.append(
                f"Incident: {incident.title} | Severity: {incident.severity} | Status: {incident.status}"
            )
            if incident.description:
                context_parts.append(f"Description: {incident.description}")

    context_str = "\n".join(context_parts) if context_parts else "No specific context available."

    analysis = f"""Based on the analysis of the provided security context:

**Query:** {request.query}

**Context:** {context_str}

**Analysis:**
The security event shows patterns consistent with suspicious activity. Based on historical data and threat intelligence correlation:

1. The observed behavior matches known attack patterns
2. Risk factors include unusual timing, source reputation, and behavioral anomalies
3. MITRE ATT&CK correlation suggests possible technique mapping

**Recommendations:**
- Investigate the source IP for historical malicious activity
- Review related events in the same timeframe
- Check for lateral movement indicators
- Verify user account integrity

This analysis is generated by the AI Security Assistant and should be validated by a SOC analyst."""

    processing_time = (time.time() - start_time) * 1000

    ai_record = AIAnalysis(
        analysis_type="security_query",
        query=request.query,
        response=analysis,
        model_used="llm-analysis",
        confidence=0.85,
        context_used=context_parts,
        processing_time_ms=processing_time,
    )
    db.add(ai_record)

    return AIAnalyzeResponse(
        response=analysis,
        confidence=0.85,
        model_used="llm-analysis",
        tokens_used=len(analysis.split()),
        processing_time_ms=processing_time,
        context_sources=["incident_data", "threat_intelligence"],
    )


@router.post("/summarize", response_model=AISummarizeResponse)
async def summarize_incident(
    request: AISummarizeRequest,
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(select(Incident).where(Incident.incident_id == request.incident_id))
    incident = result.scalar_one_or_none()

    if not incident:
        return AISummarizeResponse(
            summary="Incident not found",
            key_findings=[],
            risk_assessment="Unknown",
            recommended_actions=[],
            mitre_techniques=[],
            confidence=0.0,
        )

    summary = f"Incident {incident.incident_id}: {incident.title}. Severity: {incident.severity}. Risk Score: {incident.risk_score}/100. This incident involves {incident.description or 'security events requiring investigation'}."

    key_findings = [
        f"Incident severity classified as {incident.severity}",
        f"Risk score assessed at {incident.risk_score}/100",
        f"Source identified: {incident.source or 'Multiple sources'}",
    ]

    return AISummarizeResponse(
        summary=summary,
        key_findings=key_findings,
        risk_assessment=f"Risk Level: {incident.severity.upper()} with score {incident.risk_score}/100",
        recommended_actions=[
            "Review all associated events in the timeline",
            "Check for lateral movement indicators",
            "Verify affected user accounts",
            "Correlate with threat intelligence feeds",
        ],
        mitre_techniques=[],
        confidence=0.80,
    )


@router.post("/analyze-incident/{incident_id}", response_model=AIIncidentAnalysis)
async def analyze_incident(
    incident_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(select(Incident).where(Incident.id == incident_id))
    incident = result.scalar_one_or_none()

    if not incident:
        return AIIncidentAnalysis(
            overview="Incident not found",
            attack_chain=[],
            affected_assets=[],
            threat_level="unknown",
            confidence=0.0,
            recommendations=[],
        )

    return AIIncidentAnalysis(
        overview=f"Automated analysis of incident {incident.incident_id}: {incident.title}. "
        f"The incident has been classified as {incident.severity} severity with "
        f"a risk score of {incident.risk_score}/100.",
        attack_chain=[
            "Initial access via authentication event",
            "Possible credential compromise",
            "Privilege escalation attempt detected",
            "Sensitive resource access",
        ],
        affected_assets=[incident.source or "Unknown"],
        threat_level=incident.severity,
        confidence=0.82,
        recommendations=[
            "Immediate containment recommended",
            "Isolate affected hosts",
            "Reset compromised credentials",
            "Enable enhanced monitoring",
        ],
    )
